image hat=Image("hat.png", yalign=0.1)
image kana=Image("kana.png", yalign=-0.1)
image cat=Image("cat.png", yalign=-0.1)
image riu=Image("riu.png", yalign=-0.1)
image nade=Image("nade.png", yalign=-0.1)
image kaavi=Image("kaavi.png", yalign=-0.1)
image hana=Image("hana.png", yalign=-0.1)
image jojo=Image("jojo.png", yalign=-0.1)
#image side hat confused=Image("side hat confused.png")
